spring.application.name=foodrescue

spring.datasource.url=jdbc:postgresql://localhost:5432/foodrescue
spring.datasource.username=postgres
spring.datasource.password=apoorva

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080